### ISSUE TITLE
[Help] How to change floppy

### ISSUE THREAD

**Issue by egrath** [kanjitalk755/macemu#127]
Hi, maybe i'm just too stupid, but how to insert/eject a floppy image when running BasiliskII? I'm running on Linux with the SDL2 renderer and the mentioned keyboard shortcut Ctrl-F1 does nothing.

**Comment by kanjitalk755** [comment]
Looking at the code, it seems that you can mount the floppy by pressing Ctrl-F1 on Linux.
However, you cannot eject.
I don't know more details because I don't have the hardware to check the operation.

You may be able to get more accurate answer by asking the question in the forum below.

https://emaculation.com/forum/

**Comment by egrath** [comment]
Thanks will take a look there!

**Comment by kanjitalk755** [comment]
P.S:
This is an operation on a floppy drive, not a floppy image.
