### ISSUE TITLE
SheepShaver crash on boot on RPI4 - "Cannot allocate memory"

### ISSUE THREAD

**Issue by demic78** [kanjitalk755/macemu#160]
Hi, I cant boot SheepShaver. I'm using a RaspberryPi400. When I launch SheepShaver i receive this message "ERROR: Cannot map first Kernel Data area: Cannot allocate memory." Some trick please? Thank you! No problem with BasiliskII...

**Comment by kanjitalk755** [comment]
I can't verify with RPI4, but how about `configure` as follows?
```
./configure --enable-addressing=direct,0x10000000
```

**Comment by demic78** [comment]
It's the same. It doesn't boot...

**Comment by ajmas** [comment]
Is there anything in the syslog that could give a clue?

**Comment by phesterman** [comment]
I've had this same error, too, even after configuring as suggested above.  Has anyone figured this out?  On the emaculation.com forum someone suggested that in sysctl vm.mmap_min_addr should equal 0, for me, this value is 4096.

**Comment by vasi** [comment]
The problem seems to be in this block: https://github.com/kanjitalk755/macemu/blob/3176aa887df7f9f98057dcf87ac467618fd6640d/SheepShaver/src/Unix/configure.ac#L1266

It causes configure to lie about the chosen direct addressing offset, so if you pass 0x10000000 configure will report 0x10000000, but actually use 0x400000000000. For some reason that address isn't available on my Pi (or yours), so allocation fails.

If you take out that block, direct addressing works fine, at least for me. Please let me know whether it works for you too.

I'm not sure how this large number 0x400000000000 was arrived at, or why we couldn't just add it to the normal address-determination range list in configure, so I'm not sure what to propose. @kanjitalk755 it looks like this is from [your commit](https://github.com/kanjitalk755/macemu/commit/d9e0761bd939ee085aa93ad7e8a5062e2e544874), can you help us understand why that number?

**Comment by kanjitalk755** [comment]
> I'm not sure how this large number 0x400000000000 was arrived at, or why we couldn't just add it to the normal address-determination range list in configure, so I'm not sure what to propose. @kanjitalk755 it looks like this is from your commit, can you help us understand why that number?

This constant comes from the thread below.

https://www.emaculation.com/forum/viewtopic.php?t=11143

The block has been modified to be used only for Mac.

**Comment by vasi** [comment]
Thanks! I think we can close this then.

**Comment by kanjitalk755** [comment]
@demic78 @phesterman Try again following command with latest source.

```
./configure --enable-addressing=direct,0x10000000
```

If the problem persists, please let me know.

**Comment by pzskc383** [comment]
Posting this to confirm: sheepshaver refused to build on my arm64 machine until i set adressing to direct (without parameter)
