### ISSUE TITLE
Easy Install : MacOSX Ventura (Intel) Basilisk II and SheepShaver 

### ISSUE THREAD

**Issue by snakebyte69** [kanjitalk755/macemu#168]
Basilisk II GUI 64bit Version
Download version 0.20: https://www.emaculation.com/basilisk/Basilisk-II-GUI-0.20.zip

Basilisk II 64bit Version - Beta
https://www.emaculation.com/basilisk/BasiliskII_universal_20230610.zip

search for:
- PERFORMA ROM
- System 7.5.3.dmg

Create a Folder
/Applications/BasiliskII

Copy everything into there

Run Basilisk II GUI first to configure

configuration file location
~/.basilisk_ii_prefs

-----

SheepShaver 64Bit Version
https://www.emaculation.com/sheepshaver/SheepShaver_universal_20230713.zip

Search for:
- 1999-05-14 - Mac OS ROM 1.6.rom
- Apple MacOS 9.0.4.iso

Copy everything into
/Applications/SheepShaver

To configure goto
- SheepShaver
 - Settings

*** For Trouble Shooting ***
Right click on the App and select "Show Package Contents"
Select
- Contents
 - MacOS

configuration file location
~/.config/SheepShaver/prefs

Run applications from this folder for the terminal version so you can see errors
- "ERROR: Cannot open ROM file." - Means it can't find the ROM file
- "ERROR: Invalid ROM file size. Basilisk II requires a 512K or 1MB MacII ROM." - Means the ROM is not compatible

**Comment by RonaldPR** [comment]
Yes. That would be a short version of the more elaborate setup manual here:
https://www.emaculation.com/doku.php/basiliskii_osx_setup
You would not have had your problems if you had followed that manual in the first place.

**Comment by dhorlick** [comment]
> That would be short versions of the more elaborate setup manuals

snakebyte69's easy installation instructions provide at least one piece of information which appears to be incorrect in the "elaborate" setup manual for Sheepsaver:

> configuration file location
> ~/.config/SheepShaver/prefs

The "elaborate" Sheepsaver setup manual (not even mentioned in the project README…) provides this location as `~/.sheepshaver_prefs`.

This also appears to be incorrect in the "Sheepsaver scripts" folder linked from the forum topic…

**Comment by RonaldPR** [comment]
Which SheepShaver version/build/setup do you use? Possibly a customised pre-configured SheepShaver release?

With a regular SheepShaver for macOS setup the settings are saved in **~/.sheepshaver_prefs**
I used many SheepShaver versions since 2006, on successive MacOSX/OSX/macOS versions, and I never had, and still do not have, a file **~/.config/SheepShaver/prefs**

**Comment by snakebyte69** [comment]
~/.config/SheepShaver/prefs
Is the folder that was created on my Mac when SheepShaver is run

**Comment by dhorlick** [comment]
> Which SheepShaver version/build/setup do you use?

I am using https://www.emaculation.com/sheepshaver/SheepShaver_universal_20231229.zip on an M2 Mac Mini running macOS Sonoma.

Admittedly, this is not one of the [formal repository releases](https://github.com/kanjitalk755/macemu/releases). But it _is_ the download recommended in the elaborate setup manual:

> Download both SheepShaver Folder and SheepShaver application from [this forum topic](https://www.emaculation.com/forum/viewtopic.php?f=20&t=7360).

which in turn recommends:

> • Version 2.5, 29 December 2023, universal (x86_64 and arm64) from github.com/kanjitalk755/macemu source
Universal, will run natively on both Intel and Apple Silicon.
Recommended for macOS 10.13 (High Sierra) through macOS 14 (Sonoma).
Download: [https://www.emaculation.com/sheepshaver ... 231229.zip](https://www.emaculation.com/sheepshaver/SheepShaver_universal_20231229.zip)

**Comment by RonaldPR** [comment]
> ~/.config/SheepShaver/prefs Is the folder that was created on my Mac when SheepShaver is run

Very unusual. Maybe kanjitalk755 can explain this.

>  ~/.config/ is common for a lot of apps

I have 140+ applications on my Mac and I do not even have a ~/.config/ folder. (Yes, I checked for hidden folders and yes, I checked with Terminal.)

**Comment by RonaldPR** [comment]
> Admittedly, this is not one of the [formal repository releases](https://github.com/kanjitalk755/macemu/releases). But it _is_ the download recommended in the elaborate setup manual:

These "formal repository releases" are early, 5 year old, pre-releases. The downloads recommended in the manual are all compiled from this repository, from the state of the source at the build date, using the method outlined here.

**Comment by emendelson** [comment]
There's clearly some version of SheepShaver out there that creates the config file in ~/.config/SheepShaver, because I found that folder on my disk, complete with a prefs file. I have no idea of how it got there.

The macOS-default location should be ~/Library/Application Support/SheepShaver, and the file should be visible. Maybe kanjitalk would consider making that the default location for the prefs file, but if the file isn't found there, the app would use an existing prefs file in the user folder, where it is now? That would mean that any new install would use ~/Library/Application Support, but any existing file would be respected.

**Comment by RonaldPR** [comment]
Let us not (yet) complicate this discussion with suggestions for changing the prefs file location.

Apparently some applications save settings in a ~/.config/appname/ folder and create the ~/.config/ folder while doing that. I have no ~/.config/ folder so apparently I do not have applications that do that.

SheepShaver will normally save its settings in a ~/.sheepshaver_prefs file. Numerous discussions in Emaculation SheepShaver forum confirm that.

@ emendelson
Is your ~/.config/SheepShaver/prefs file identical to your ~/.sheepshaver_prefs file ?
If the prefs files are not identical, which one is used by SheepShaver?

**Comment by dhorlick** [comment]
It looks like it might prefer certain locations based on whether particular sub-directories exist or not…

https://github.com/kanjitalk755/macemu/blob/0a1d9c35bfdb4a386d628fca16be791cc4a7ba26/BasiliskII/src/Unix/prefs_unix.cpp#L134

**Comment by emendelson** [comment]
@RonaldPR - The file in ~/.config/ did not have a `disk` entry and was clearly ignored by the latest version of SheepShaver. I deleted the file in ~/.config and SheepShaver opened with the prefs in ~/, exactly as it did before.

**Comment by kanjitalk755** [comment]
These specifications originate from #144.

**Comment by RonaldPR** [comment]
This is very confusing and it complicates support as several settings need to be manually edited using a text editor. Different users now have the prefs file in different locations.

And why would macOS applications need to follow current Linux specifications? This makes no sense. At the time I thought it would only apply to Linux versions.

If we want to follow what is usual in macOS, the prefs file should be **~/Library/Application Support/SheepShaver/prefs** as emendelson suggests.

But changing the location of the prefs file will still result in support issues. Maybe a new SheepShaver (and BasiliskII) version with changed prefs file location should move an existing prefs file to the new location.

**Comment by dhorlick** [comment]
I don't disagree, but to me the more serious issue is that the (external) documentation and folder scripts are incorrect.

I also feel like the documentation should be copied to or linked from the project README here. If someone happens upon this GitHub repository, they might be able to build SheepShaver and Basilisk II, but would likely lack the necessary context to operate them.

Since it's a fork, it would probably also be helpful if the repository bore some definitive statement of its endorsement by the original author for ongoing work.

(By the way, thanks for these applications!)

**Comment by RonaldPR** [comment]
I am the one who publish the SheepShaver (and BasiliskII) builds from kanjitalk755 source, I am the one who wrote the setup manuals, and I am the one who wrote the scripts.

Until this week I was completely unaware of the fact that for new users the prefs and nvram files are saved in ~/.config/SheepShaver/

"new users" are users who never used SheepShaver before, who have no pre-existing prefs and nvram files in their Home folder, and who installed a build that was created after 1 October 2022.

I regret the changed location of these files. It causes confusion and it solves nothing. If I had been aware that this change was not only for Linux hosts but also for macOS, I would certainly have advised against it.

Yes, of course I will adjust the manual and the scripts. The scripts must work for old and new users. Maybe I will add a script that will open the prefs file for editing regardless the old or new location.

I am busy with a lot of things, so it may take some time.

The issue does not affect BasiliskII because both BasiliskII itself and the stand alone GUI app still save the hidden prefs and xpram files in the Home folder.

**Comment by dhorlick** [comment]
> I am the one who publish the SheepShaver (and BasiliskII) builds from kanjitalk755 source, I am the one who wrote the setup manuals, and I am the one who wrote the scripts.

Indeed, hence my thanks.

> Yes, of course I will adjust the manual and the scripts.

Thank you, again! For what it's worth, I have been using:

```zsh
#!/bin/zsh
rm -Rf "~/Library/Saved Application State/com.emaculation.sheepshaver.savedState"
rm -Rf ~/.config/SheepShaver
rm ~/Library/Preferences/SheepShaver.plist
rm ~/Library/Preferences/com.emaculation.sheepshaver.plist
rm ~/.sheepshaver_prefs 
rm ~/.sheepshaver_nvram
```

All the above files are either mentioned in the documentation, or have appeared on my computer after using one version or another.

> I am busy with a lot of things, so it may take some time.

Of course! By no means did I intend to rush anyone. I was merely speaking about the relative priority of the documentation edits versus the changing the application configuration behavior.

**Comment by kanjitalk755** [comment]
For macOS, reverted prefs and xpram(nvram) location.

**Comment by RonaldPR** [comment]
Oops! I said that I regret the change, but that was not a request to reverse it after more than a year. What does this mean for users who now have the prefs and nvram files in ~/.config/SheepShaver/ ? Will future SheepShaver builds still use these files or will the affected users need to set up SheepShaver again from scratch when they install an updated build?

I could write a script that moves and renames the files to the new (old) location.

**Comment by kanjitalk755** [comment]
If it works properly with the latest source, the files under `.config/` are not necessary because the 
prefs file in the home directory has been read from before.

Otherwise, you will need to move the files under `./config` to your home directory.

```
cd
mv .config/BasiliskII/prefs .basilisk_ii_prefs
mv .config/BasiliskII/xpram .basilisk_ii_xpram
rmdir .config/BasiliskII/
mv .config/SheepShaver/prefs .sheepshaver_prefs
mv .config/SheepShaver/nvram .sheepshaver_nvram
rmdir .config/SheepShaver/
```

**Comment by RonaldPR** [comment]
The problem does not exist with BasiliskII as recent BasiliskII builds do not create prefs and xpram files in ~/.config/

The problem exists only for users who created a new SheepShaver setup with a SheepShaver build that was compiled after 1 October 2022. Most will be unaware where the prefs file is created and will be unpleasantly surprised to see that their working SheepShaver setup suddenly does not work anymore after a new upgrade.

Many users will be hesitant to use the command line. Before I will post a new SheepShaver build, I will make a notarized AppleScript app that can be run before a next upgrade regardless where the prefs file is. The nvram file is not really important, a new one will be created.

The script will look something like this:
```
try
	do shell script "if test -f ~/.sheepshaver_prefs; then
		:
	else
		mv ~/.config/SheepShaver/prefs ~/.sheepshaver_prefs
	fi"
end try
```
I may add a line to remove the ~/.config/SheepShaver/ folder. The script will leave the ~/.config/ folder alone. Although unlikely, you never know what else it may contain for some users.

I will also modify the existing delete scripts for the SheepShaver folder to be compatible with both situations:
(The SheepShaver folder is used to set up SheepShaver following my setup guide.)
```
try
	do shell script "rm ~/.sheepshaver_prefs || true
	rm ~/.config/SheepShaver/prefs || true"
end try
```
and I will add an "Edit prefs file" script to the SheepShaver folder that will open the prefs file in a text editor regardless where it is located.
