### ISSUE TITLE
Feature request: For SDL2, in keycode mode, allow remapping of modifier keys

### ISSUE THREAD

**Issue by rakslice** [kanjitalk755/macemu#28]
In SDL2 keyboard handling, for the case where `keycodes` is enabled, host modifier keys are specifically excluded from the cases that provided mapping:

https://github.com/kanjitalk755/macemu/blob/c23967b03bb03e2d11665e22c71c0db1de351dfc/BasiliskII/src/SDL/video_sdl2.cpp#L2213

https://github.com/kanjitalk755/macemu/blob/c23967b03bb03e2d11665e22c71c0db1de351dfc/BasiliskII/src/SDL/video_sdl2.cpp#L2244

This prevents re-mapping of modifier keys. This is inconvenient.

This was put in for SDL in b6e1e6e53689326c76f415569bfc52f4cac125b7 , at the same time as some SDL Mac OS X keyboard fixes, so perhaps the modifier change is for SDL on Mac OS X also? Is it necessary to avoid a problem of some kind?

Is this also true for SDL2?

If the exception for modifiers is not needed for SDL2 it could simply be removed.

Alternatively, if it _is_ necessary to handle modifiers as keysyms for whatever reason, another approach would be to add logic that infers the keysym remappings for modifiers from the keycodes table and applies them on the keysyms side.

**Comment by kanjitalk755** [comment]
I don't understand the intention of excluding modifier keys from customizing keymaps.
So, I tried to be able to define modifier keys in the keymap file.

Please test:
https://github.com/kanjitalk755/macemu/tree/test_keymap

**Comment by rakslice** [comment]
I tested this branch in Mac OS X 10.12 and Linux, working around #29, and the keyboard remapping works fine.

**Comment by kanjitalk755** [comment]
Merged to the master.

**Comment by BloodyMess** [comment]
I'm having a problem related to this, but I'm not sure if it should be under this issue or a new one.

My system config is this:
SOFTWARE:

- elementary OS 5.1.7 Hera (with all current updates) based on Ubuntu 18.04LTS
- Linux Kernel 5.4.0-48-generic
- GTK 3.22.30
- SheepShaver built from a current snapshot of master branch from this repository.

HARDWARE:

- Ryzen 3900X
- Radeon RX590
- 128GB RAM
- Matias Tactile Pro Keyboard for Mac

As you can see above, I'm using a keyboard made for Macs on my Linux system. I'm trying to get my SheepShaver Mac to use the correct command and option keys on my Mac keyboard.

Other builds I've been running previously (from vasi, as posted on the e-maculation forums) have swapped the command and option keys and also would only respond to the left command and option keys, ignoring the right-hand command and option keys.

I ran across this issue searching for a solution, and downloaded a snapshot to see if your SheepShaver was any better. I looked at the code in video_sdl2.cpp and found the places where the keycodes were being swapped unless the __APPLE__ macro is defined. Since swapping those keys isn't appropriate for the Mac keyboard I'm using, I commented out the #ifdef and related #else block, leaving just the code that leaves the keycodes as they are.

This mostly worked! But there is an odd bug that I cant' figure out so far: when I press a command-key combination it seems to be sending the regular keypress first and then immediately follows it with the correct command-key combo that I pressed. For Example:

1. At the Finder Desktop, Press command-N to create a new folder. This creates a folder presenting the "untitled" text for you to edit.
2. WITHOUT pressing any other keys or clicking the mouse anywhere, press command-I to open the Get Info window.
3. You'll see that the name of the folder has been changed to an "i" and THEN the Get Info window was opened for the folder.

The order that these key events happens in can be verified like this:

1. In the Finder (at Desktop or with a folder window active, it doesn't matter) with nothing selected, press command-i.
2. The Finder will process the plain "i" keypress by selecting the icon with the closest matching name , and then opening the Get Info window.

Like i said earlier, I don't know if this should be under this issue or in its own issue.

Also, I'm not sure whether it should be a bug or a feature request to not swap the command and option keys when a Mac keyboard is being used regardless of whether the system itself is a Mac.
