### ISSUE TITLE
SheepShaver for Windows issues

### ISSUE THREAD

**Issue by cat7** [kanjitalk755/macemu#55]
Hi,

I just compiled SheepShaver for Windows using msys2 32 bit.
Initial testing shows some issues with the build. I use a new world rom.
-I cannot boot from CD image or real CD.
-I have no sound in Mac OS 9.0 or 8.6. 

8.6 has a long pause during boot (checking sound hardware?) and hangs when selecting alert sounds. 
In Mac OS 9.0 the sound extension doesn't show a version number and opening the sound control panel shows an error of type -199. SheepShaver then crashes.

Best,
Howard

**Comment by kanjitalk755** [comment]
inspection results:

boot from CD image: OK
sound in Mac OS 9.0.4: OK
sound in Mac OS 8.6: no good

Tell me the commit hash if you know the version that works fine in Mac OS 8.6.

**Comment by cat7** [comment]
Hi,

The sound issue in Mac OS 9 was solved by a fresh installation using my old 2015 build. As it turned out, my dvd rom drive was broken and I had to replace it first ;-) This at least proves my installation CD is OK.
 
However, I still cannot boot from CD or image with the msys2 build. The CD is ejected at boot, the image is not recognized and Mac OS asks to initialize the disk image. Perhaps I'm missing some package in msys2, or there is an issue in my host? To eliminate a build/host error, I uploaded the build here: https://surfdrive.surf.nl/files/index.php/s/XGhwnNMbv6vQqtj/download
Perhaps you can try to run it?

I know no known good commit for the audio issue in Mac OS 8.6

Best,
Howard

**Comment by kanjitalk755** [comment]
Your build can boot Mac OS 9 CD image successfully.
Host: Windows 10

In Mac OS 8.6, the sound is OK if Old World ROM is used.

**Comment by cat7** [comment]
Well, no idea yet of what is going on. I had to re-image some CDs to get SheepShaver to boot from them...
Still no boot from the same real CDs. I'll come back to this later if a brand new cd player will not solve the issue.

**Comment by rakslice** [comment]
There is a quirk with SheepShaver in some configurations, in that a sound output device is not selected within the emulated Mac OS by default, in a way I presume that never happens on real hardware. 

Per (https://www.emaculation.com/forum/viewtopic.php?f=20&t=8267), in Mac OS 8.5/8.6, the default Monitors & Sound control panel does not provide a way to select the sound output device, but the installation provides the old Sound control panel in the Apple Extras folder, and its third page, "Sound Out", allows selecting the output device.

Sound works for me in 8.5 with newworld ROM with the current code after I do this.

**Comment by cat7** [comment]
Thanks!
I can, however, still not boot or read real CDs with a Windows build from the current code.

**Comment by rakslice** [comment]
The platform-specific `SysAddCDROMPrefs` is locating CD-ROMs but they aren't being used.

I think the problem is the change in 23da9e72ebef35f3cf67b0a443cad09ad0ee28ff . In the case where no CD-ROMs are configured, the `if` block runs the platform-specific `SysAddCDROMPrefs()` to find CD-ROMs and add them to the loaded prefs but the code to then actually use the values that are in the prefs is moved to a corresponding `else` block so doesn't happen in that case.

Does using detected CD-ROMs create some other problem for what you were trying to do there @spolsley?

**Comment by rakslice** [comment]
This isn't the entire problem, but it could be the first part of it.

**Comment by rakslice** [comment]
Subsequently it opens a file handle to the drive and reads the TOC successfully, but then tries to do reads using the old `cdenable` driver which doesn't exist. If I instead modify it to do regular I/O on the file handle that works fine; I wonder if something has subtly changed in the `file_handle` flags settings or meanings...

**Comment by spolsley** [comment]
Ah, this is an interesting blend of issues.  In MacOS, the /dev/poll/cdrom was causing a crash—I thought due to bincue attempting to open the file handle, but it was more likely the drive iterator kanjitalk fixed in d906fb2.  I'd also partly misunderstood the SysAdd function for not adding a file handle, but it didn't come up on the Mac where physical CDs no longer work.

I'd say that change in 23da9e7 should be reverted.  However, it may be further tied to the bincue code attempting to load every cdrom as a cue sheet.  Initially, bin/cue pairs were loading as unreadable images, so I had to [change the flag](https://github.com/kanjitalk755/macemu/pull/45/commits/30cf26e1f6e42e09ca9b32a23c7ce8dd3566fd69#diff-58e5a2da5e67276566e0464bd80e5b1c) to open the file as a binary.  Perhaps this is interfering with the actual CD paths.

If it is working without bincue, I think it might solve it to add a pre-load validation which confirms the filename is a ".cue" path before attempting to parse it.  Ideally, nothing changes for regular CDs or non-cue files when bincue is enabled, and it sounds like that's not happening.

**Comment by spolsley** [comment]
It occurs to me that requiring ".cue" in the filename could save trouble trying to parse non-cue files, but it does add a requirement on the user side for their image names.  Much of the bincue code is drawn from DosBox, in which they make no assumptions about filenames, validating contents by trying to load as different types: [dosbox/cdrom_image.cpp#L164](https://github.com/FruitieX/dosbox/blob/master/src/dos/cdrom_image.cpp#L164).

I'll try to locate my old Mac OS 8 discs to test as well.

**Comment by rakslice** [comment]
Nothing about this is related to bin/cue, I was just asking about the change in 23da9e7

**Comment by rakslice** [comment]
As far as physical CD's in macOS goes, is this something new, or just needing to be in the `operator` group to have permission to access the raw disk device, which you can do with:
```
dscl . append /Groups/operator GroupMembership you
```

**Comment by spolsley** [comment]
I'm relieved if it's not bincue!  I was concerned given no other recent changes to sys_windows.  Looks like you may have resolved it, and backing out the change in 23da9e7 seems fine.  I haven't encountered a crash testing with the change.

The lack of physical CD support on Macs has been around for a while, at least since Mac OS 10.8 from 2012.  I don't know that anyone's actually looked into it since Macs stopped including optical drives around that time.  It may well be just a permissions issue.

**Comment by cat7** [comment]
Hi,

I could read real CDs on MacOS host when running SheepShaver as root. 
I'll try the Windows patch. Meanwhile, I noticed I can read real CDs on Linux host, but the pref cdrom /dev/cdrom has to be added to the prefs first.

**Comment by rakslice** [comment]
Yeah, I noticed that too, in regard to the GUI option to boot from CDROM having no effect in SheepShaver, although the corresponding option in Basilisk II works on the same host system; I'll see if I can figure out what's happening.

**Comment by rakslice** [comment]
It's just newworld that is unaffected by the CDROM boot option; it hasn't even read XPRAM locations `137a` & `137b` by time it is booting from a volume other than the CD, or at least it doesn't read them using the XPRAM/NVRAM ops SS in `emul_op.cpp`. Perhaps there is some other NVRAM location for the boot setting, or maybe another setting that needs to be set first to tell it to even check?

**Comment by kanjitalk755** [comment]
It was still in the middle, so I reopened it.

**Comment by rakslice** [comment]
Ok, the XPRAM 4 bytes starting at `1378` are being read, I just can't figure out what effect they have on the selection of the boot volume with newworld, if any.  Changing that setting, reordering the ref numbers, and volume numbers all have no effect on the first bootable disk provided by `.ATADisk` becoming the boot device if one is present.

**Comment by rakslice** [comment]
Have the `bootdriver`, `bootdrive`, or similar settings ever worked in SheepShaver with newworld ROM in the past?

**Comment by rakslice** [comment]
I see the Mac OS 9 Startup Disk control panel doesn't crash SS like the 8.5/8.6 version, and it sets the 4 bytes of XPRAM at offset `1378` to the drive number and the expected driver ref num like what we set via `bootdriver` for CDROM boot, but it doesn't actually affect anything when rebooting -- it just boots the first drive of `.ATADisk` like always.

**Comment by rakslice** [comment]
The `.ATADisk` used to very recently be just `.Disk`, but that doesn't affect the problem, even the upstream code which still uses `.Disk` is affected.

**Comment by cat7** [comment]
I checked some older builds I provided on emaculation. The notes accompanying the last build (from 2015!) did already mention this as an issue. I vaguely remember that build was the first using the updated CD reading code Lauri provided to allow access to CDs on 64-bit Windows (also eliminating reliance on the cdenable.sys driver).

**Comment by rakslice** [comment]
Aha, those would be with the changes from https://macintoshgarden.org/forum/basilisk-ii-old-windows-builds-lauri-pesonen#comment-73774 ? I knew that feature had existed before, but I didn't realize it was never in the upstream codebase.

**Comment by cat7** [comment]
yes, that is the correct. I didn't check whether it went into kanji's codebase.

**Comment by cat7** [comment]
Nasty as it may be, it works....
Thanks!
