### ISSUE TITLE
Merge changes from SegHaxx / macemu-flatpak?

### ISSUE THREAD

**Issue by webspacecreations** [kanjitalk755/macemu#85]
https://github.com/emaculation/macemu/issues/150 mentions Basilisk II fixes related to JIT made on top of this kanjitalk755 repo that incorporate a few additional fixes from cebix.

Repo is https://github.com/SegHaxx/macemu-flatpak. Hope you'll consider wrapping the useful bits into this repo as this is one of the most active / "official"

**Comment by kanjitalk755** [comment]
This repository is used for binary distribution at following site and carelessly merging can cause problems.

https://emaculation.com/forum/

I took a quick look, but I didn't find any features that I thought should be merged.
What features do you think it should be merged from the Flatpak fork?

**Comment by SegHaxx** [comment]
To be clear I have not published my full memory/JIT fixes publicly yet, what's in my master, at commit 0c8529ec merges cebix repo into this one. Merging it would be useful because then cebix and this one are in-line, and thus the path is clear to merge kanjitalk755 into cebix. :)

The new features i found include:

1) The 24-bit addressing and some other stuff all appears in support of emulating a Mac Classic ROM in order to run System 6.x on Basilisk. It requires compiling with "banked" addressing to work. I've not actually tested this. But it's all well isolated.

2) A feature to make windows dynamically resizeable

3) Support for VDE networking on Linux. I have not tested this either, but this is a new standard for what the old sheepnet did.

**Comment by kanjitalk755** [comment]
> The 24-bit addressing and some other stuff all appears in support of emulating a Mac Classic ROM in order to run System 6.x on Basilisk. It requires compiling with "banked" addressing to work. I've not actually tested this. But it's all well isolated.

This is not practical due to the following problems.

- CPU usage sticks to 100% even when idling
- Incompatible with JIT compiler

I think Mini vMac is suitable when using System 6.

> A feature to make windows dynamically resizeable

This fork also supports window scaling, but only in integer multiples. The reason for not making it dynamic is:

- Ugly when set to nearest sampling
- SheepShaver's hardware cursor doesn't work (macOS)

> Support for VDE networking on Linux. I have not tested this either, but this is a new standard for what the old sheepnet did.

I adopted it.
